### ISSUE TITLE
Changed holidays to accommodate Tokyo Olympics

### ISSUE THREAD

**Issue by paddy-hack** [emacs-jp/japanese-holidays#21]
Hi, I just wanted to point out that a few holidays have been moved around for 2021.

| holiday | from | to |
|-----------|--------|----|
| 海の日 | 2021-07-19 | 2021-07-23 |
| スポーツの日 | 2021-10-11 | 2021-07-24 |
| 山の日 | 2021-08-11 | 2021-08-08 |

That last day is a Sunday, so 2021-08-09 becomes 振替休日.

Can you please update `japanese-holidays.el` to reflect this :bow:

**Comment by conao3** [comment]
.go.jp source: https://www.kantei.go.jp/jp/headline/tokyo2020/shukujitsu.html
