### ISSUE TITLE
Update for upcoming change of emperor

### ISSUE THREAD

**Issue by paddy-hack** [emacs-jp/japanese-holidays#6]
Japan is going to get a new emperor on 2019-05-01.  Related to this there will be a few changes in the Japanese holidays for 2019 and beyond.  I am aware of the following

 - emperor's birthday, from *-12-23 until 2018 to *-02-23 from 2020 (天皇誕生日)
 - current emperor stepping down on 2019-04-30 (天皇陛下退位)
 - crown prince ascending throne on 2019-05-01 (皇太子様即位)
 - 2019-10-22 (即位礼正殿の儀)

I'd prepare a PR if it weren't for all the comments in the current file that add references to the various laws and official announcements (or whatever they're called) that corresponds to the above.  I have zero information on those.

**Comment by paddy-hack** [comment]
@kawabata I just saw 4045e6620cbeb98e4828aa1d9c420bc429441f00 and thought it was strange that the date and description didn't match the info I provided in this issue (which is based on my company calender :innocent:).  Using the comment you added in the diff, I found a [government page](https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html) which seems to indicate you mixed things up a bit.  Quoting from that page:

> 「天皇の即位の日及び即位礼正殿の儀の行われる日を休日とする法律」について
>
> 天皇の即位の日の平成31年（2019年）5月1日及び即位礼正殿の儀が行われる日の平成31年（2019年）10月22日は、休日となります。また、これらの休日は国民の祝日扱いとなるため、平成31年（2019年）４月30日と５月２日も休日となります

Please check again :bow:

**Comment by iquiw** [comment]
@paddy-hack I think you are right, sent PR #7 for it. Hope it is OK.

**Comment by paddy-hack** [comment]
@kawabata :bowing_man: 

One more thing, though.  I *believe* there was talk about moving 即位礼正殿の儀 to May.  I vaguely remember seeing this in the news but am not sure.

**Comment by kawabata** [comment]
hello @paddy-hack, I don't know about that discussion, but the government officially announced that ascension will be done in May 1st and ceremony will be on October.
cf. https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html

**Comment by paddy-hack** [comment]
Thanks for checking.  Like I said, I wasn't quite sure about it. :wink:
